services:
  - type: web
    name: pinaka-ai
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:app
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true