services:
  - type: web
    name: pinaka-ai
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:app
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: YOLO_CONFIG_DIR
        value: /tmp/yolo_config